name: _Base Runtime (shared)

on:
  workflow_call:
    inputs:
      base_url:
        required: false
        default: "https://test-eprihlasky.iedu.sk"
        type: string

      idp_url:
        required: false
        default: "https://tiamidsk.iedu.sk"
        type: string

      username:
        required: false
        type: string

      password:
        required: false
        type: string

      python_command:
        required: true
        type: string

      extra_env:
        required: false
        default: ""
        type: string

    secrets:
      LOGIN_USERNAME:
        required: false
      LOGIN_PASSWORD:
        required: false

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ inputs.base_url }}
      IDP_URL:  ${{ inputs.idp_url }}

      LOGIN_USERNAME: ${{ inputs.username || secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ inputs.password || secrets.LOGIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 locust pandas matplotlib reportlab

      - name: Validate credentials presence
        run: |
          if [ -z "${LOGIN_USERNAME}" ] || [ -z "${LOGIN_PASSWORD}" ]; then
            echo "‚ùå Missing LOGIN_USERNAME or LOGIN_PASSWORD"
            exit 1
          fi

      - name: Run test
        run: |
          set -e
          ${{ inputs.extra_env }}
          ${{ inputs.python_command }}
